---
# tasks file for ansible-role-nsd

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Create db directory
  file:
    path: "{{ nsd_db_dir }}"
    mode: 0755
    owner: "{{ nsd_user }}"
    group: "{{ nsd_group }}"
    state: directory
  notify: Restart nsd

- name: Create nsd.conf
  template:
    src: nsd.conf.j2
    dest: "{{ nsd_conf }}"
  notify: Restart nsd

- include: configure-remote.yml
  when: nsd_remote_enable

- name: Start nsd
  service:
    name: "{{ nsd_service }}"
    enabled: true
    state: started
